[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.6",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt[crypto]>=2.14.0",
    "sqlmodel>=0.0.42",
    "svix>=2.5.0",
    "uvicorn[standard]>=0.53.0",
]
